### ISSUE TITLE
Item Menu

### ISSUE THREAD

**Issue by White-Edward** [White-Edward/theHunt#13] opened 2016-03-30 03:03 UTC
## The AidBag and ClueBag need a little attention

| Item Menu |
| --- |

 C - Clue bag
 T - TNT
 P - Old cell phone
 M - Monkey
 A - Aid Bag
##  B - Back to the main menu

Select an option: a
**\* startAidBag function called ***

Select an option: c
**\* startClueBag function called ***

**Comment by Lloyd-Ann** [comment] 2016-04-02 03:49
This ends up being part of fleshing out each of the item menu items.  I did make it so that the item menu will only show items that the user has.  I'm going to close this issue since we have the other individual item issues open.

**Closed as completed by Lloyd-Ann** 2016-04-02 03:49 UTC

**Comment by Lloyd-Ann** [comment] 2016-04-02 03:51
Duplicate of #6 #7 #8 #9 #14
